### ISSUE TITLE
授权

### ISSUE THREAD

**Issue by MortalKim** [huang-lq/UE_VirtualCameraPlugin#3]
请问如何修改默认的待机页面（显示Github字样），需要商业授权的话费用又是多少呢

**Comment by huang-lq** [comment]
加wx：13697741598详聊


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huang-lq/UE_VirtualCameraPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月1日(星期一) 下午4:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[huang-lq/UE_VirtualCameraPlugin] 授权 (Issue #3)





 
请问如何修改默认的待机页面（显示Github字样），需要商业授权的话费用又是多少呢
